[versions]
java = "21"
kotlin = "2.2.0"
quarkus = "3.29.0"
junit = "5.11.2"
mockk = "1.13.12"
kotest = "5.9.1"
slf4j = "2.0.16"

[libraries]
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "quarkus" }
quarkus-rest = { group = "io.quarkus", name = "quarkus-rest", version.ref = "quarkus" }
quarkus-rest-jackson = { group = "io.quarkus", name = "quarkus-rest-jackson", version.ref = "quarkus" }
quarkus-hibernate-orm = { group = "io.quarkus", name = "quarkus-hibernate-orm", version.ref = "quarkus" }
quarkus-hibernate-validator = { group = "io.quarkus", name = "quarkus-hibernate-validator", version.ref = "quarkus" }
quarkus-arc = { group = "io.quarkus", name = "quarkus-arc", version.ref = "quarkus" }
quarkus-jdbc-postgresql = { group = "io.quarkus", name = "quarkus-jdbc-postgresql", version.ref = "quarkus" }
quarkus-elytron-security = { group = "io.quarkus", name = "quarkus-elytron-security", version.ref = "quarkus" }
quarkus-logging-json = { group = "io.quarkus", name = "quarkus-logging-json", version.ref = "quarkus" }
quarkus-messaging = { group = "io.quarkus", name = "quarkus-messaging", version.ref = "quarkus" }
quarkus-messaging-kafka = { group = "io.quarkus", name = "quarkus-messaging-kafka", version.ref = "quarkus" }
quarkus-kafka-client = { group = "io.quarkus", name = "quarkus-kafka-client", version.ref = "quarkus" }
quarkus-opentelemetry = { group = "io.quarkus", name = "quarkus-opentelemetry", version.ref = "quarkus" }
quarkus-cache = { group = "io.quarkus", name = "quarkus-cache", version.ref = "quarkus" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

[bundles]
quarkus-core = [
  "quarkus-arc",
  "quarkus-rest",
  "quarkus-rest-jackson",
  "quarkus-logging-json",
  "quarkus-hibernate-orm",
  "quarkus-hibernate-validator",
  "quarkus-messaging",
  "quarkus-messaging-kafka",
  "quarkus-kafka-client"
]
testing-core = [
  "junit-jupiter",
  "mockk",
  "kotest-runner",
  "kotest-assertions"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.0" }
