replicaCount: 1

image:
  repository: ghcr.io/OWNER/api-gateway
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  REDIS_URL: redis://redis:6379
  IDENTITY_SERVICE_URL: http://identity:8081
  JWT_ENABLED: "false"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

