global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/api-gateway-alerts.yml

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['host.docker.internal:8080']

